# Where the homeserver's Client-Server API is located. Typically this
# is where clients would be connecting to in order to send messages.
homeserverUrl: "https://matrix.org"

# An access token for the bot to use. Learn how to get an access token
# at https://t2bot.io/docs/access_tokens
accessToken: "YOUR_TOKEN_HERE"

# Users that can invite this bot to a room. Be careful! Each of these users will
# be able to monitor DiskStation alerts.
acceptedInviteUsers: ['@alice:example.com']

# Location on disk for where to store various bot information.
dataPath: "storage"

# Listening settings.
listen:
  # Address to bind to
  addr: "0.0.0.0"
  # Port to bind to
  port: 8080
  # `user` field in body of HTTP POST to accept
  user: "testuser"
  # `pass` field in body of HTTP POST to accept
  pass: "abc123"
